project:
  type: website
  output-dir: docs

website:
  title: "Dulitha Perera"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: false
    smooth-scroll: true
    link-external-newwindow: true

editor: visual

